---

- name: "Pull git repo"
  become: no
  ansible.builtin.git:
    repo: https://gitlab.com/qualibre-info-formations/public/misc-sources.git
    dest: /home/user/git/
  delegate_to: localhost

- name: "Copy to Machine2"
  ansible.builtin.copy:
    src: /home/user/git/ansible-files/
    dest: /var/www/html/
    owner: www-data
    group: www-data
