---

#- name: stop apache server
#  service: 
#    name: apache2
#   state: stopped

- name: install docker contenaire nginx
  community.docker.docker_container:
    name: nginx
    image: nginx
    state: started
    ports: 
      - 8080:80
